#!/usr/bin/env python3
import gzip
import io
import os
import re
import sys


def bytes_to_c_array(data, bytes_per_line=20):
    hex_bytes = [f"0x{b:02X}" for b in data]
    lines = []
    for i in range(0, len(hex_bytes), bytes_per_line):
        chunk = ", ".join(hex_bytes[i:i + bytes_per_line])
        lines.append(f"  {chunk}")
    return ",\n".join(lines)


def gzip_bytes(data: bytes) -> bytes:
    buffer = io.BytesIO()
    with gzip.GzipFile(filename="ghost_site.html", mode="wb", compresslevel=9, fileobj=buffer, mtime=0) as gz:
        gz.write(data)
    return buffer.getvalue()


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))

    html_path = os.path.join(script_dir, "ghost_site.html")
    output_gz_path = os.path.join(script_dir, "../../include/managers/ghost_esp_site_gz.h")

    os.makedirs(os.path.dirname(output_gz_path), exist_ok=True)

    try:
        from htmlmin import minify as html_minify
        from csscompressor import compress as css_compress
        import jsmin
    except ImportError:
        print("Error: Required libraries not found. Installing them now...")
        install_dependencies()
        from htmlmin import minify as html_minify
        from csscompressor import compress as css_compress
        import jsmin

    try:
        with open(html_path, 'r', encoding='utf-8') as f:
            html_content = f.read()
    except Exception as e:
        print(f"Error reading HTML file: {e}")
        sys.exit(1)

    print(f"Original HTML size: {len(html_content)} bytes")

    def minify_css(match):
        css_content = match.group(1)
        try:
            minified = css_compress(css_content)
            return f"<style>{minified}</style>"
        except Exception as e:
            print(f"Warning: Error minifying CSS: {e}")
            return match.group(0)

    html_content = re.sub(r'<style>(.*?)</style>', minify_css, html_content, flags=re.DOTALL)

    def minify_js(match):
        js_content = match.group(1)
        try:
            minified = jsmin.jsmin(js_content)
            return f"<script>{minified}</script>"
        except Exception as e:
            print(f"Warning: Error minifying JavaScript: {e}")
            return match.group(0)

    minified_html = re.sub(r'<script>(.*?)</script>', minify_js, html_content, flags=re.DOTALL)

    try:
        minified_html = html_minify(minified_html,
                                    remove_comments=True,
                                    remove_empty_space=True,
                                    remove_all_empty_space=False,
                                    reduce_boolean_attributes=True)
    except Exception as e:
        print(f"Warning: Error minifying HTML: {e}")
        print("Using original HTML content...")
        minified_html = html_content

    minified_bytes = minified_html.encode('utf-8')
    print(f"Minified HTML size: {len(minified_bytes)} bytes")

    gz_bytes = gzip_bytes(minified_bytes)
    gz_header_content = f"""/* Generated by html_to_header.py, do not edit manually */

/* Contents of file ghost_site.html (gzip compressed) */
const long int ghost_site_html_gz_size = {len(gz_bytes)}UL;
const unsigned char ghost_site_html_gz[{len(gz_bytes)}UL] = {{
{bytes_to_c_array(gz_bytes)}
}};
"""

    try:
        with open(output_gz_path, 'w', encoding='utf-8') as f:
            f.write(gz_header_content)
        print(f"Successfully generated gzip header file: {output_gz_path}")
        ratio = (len(gz_bytes) / len(minified_bytes) * 100) if minified_bytes else 0
        print(f"Gzip size: {len(gz_bytes)} bytes (ratio {ratio:.2f}%)")
    except Exception as e:
        print(f"Error writing gzip header file: {e}")
        sys.exit(1)


def install_dependencies():
    import subprocess

    dependencies = ["htmlmin", "csscompressor", "jsmin"]

    try:
        for dep in dependencies:
            print(f"Installing {dep}...")
            subprocess.check_call(
                [sys.executable, "-m", "pip", "install", dep]
            )
        print("All dependencies installed successfully!")
    except subprocess.CalledProcessError as e:
        print(f"Error installing dependencies: {e}")
        print("Please install the following manually:")
        print("  pip install htmlmin csscompressor jsmin")
        sys.exit(1)

if __name__ == "__main__":
    main() 