#ifndef MANAGERS_AUTH_DIGEST_H
#define MANAGERS_AUTH_DIGEST_H

#include <stddef.h>

// Generate a stateless nonce using HMAC-SHA256(key, ts) and base64-encode "<ts>:<hmac_hex>".
// out is NUL-terminated on success. Returns 0 on success, negative on error.
int generate_stateless_nonce(const char *key, size_t key_len, char *out, size_t out_len);

// Validate a stateless nonce previously generated by generate_stateless_nonce.
// skew_s is allowed time skew in seconds. Returns 0 on valid, negative on invalid/expired.
int validate_stateless_nonce(const char *key, size_t key_len, const char *nonce, unsigned int skew_s);

// Compute HTTP Digest response (RFC2617) using MD5. Supports qop="auth" when qop, nc and cnonce supplied.
// Produces lowercase hex NUL-terminated response in out.
int compute_digest_response(const char *username, const char *realm, const char *password,
                            const char *method, const char *uri,
                            const char *nonce, const char *cnonce, const char *nc,
                            const char *qop, char *out, size_t out_len);

#endif // MANAGERS_AUTH_DIGEST_H


