#ifndef INFRARED_PROTOCOLS_H
#define INFRARED_PROTOCOLS_H

#include "infrared_common.h"

extern const InfraredCommonProtocolSpec infrared_protocol_nec;
extern const InfraredCommonProtocolSpec infrared_protocol_kaseikyo;
extern const InfraredCommonProtocolSpec infrared_protocol_pioneer;
extern const InfraredCommonProtocolSpec infrared_protocol_rca;
extern const InfraredCommonProtocolSpec infrared_protocol_samsung;
extern const InfraredCommonProtocolSpec infrared_protocol_sirc;
extern const InfraredCommonProtocolSpec infrared_protocol_sirc15;
extern const InfraredCommonProtocolSpec infrared_protocol_sirc20;
// TODO: extern declarations for other protocols
extern const InfraredCommonProtocolSpec infrared_protocol_rc5;
extern const InfraredCommonProtocolSpec infrared_protocol_rc6;
extern const InfraredCommonProtocolSpec infrared_protocol_necext;

#endif // INFRARED_PROTOCOLS_H 