#ifndef INFRARED_TIMINGS_H
#define INFRARED_TIMINGS_H

// Kaseikyo (Panasonic) protocol timings
#define INFRARED_KASEIKYO_UNIT               432
#define INFRARED_KASEIKYO_PREAMBLE_MARK      (8 * INFRARED_KASEIKYO_UNIT)
#define INFRARED_KASEIKYO_PREAMBLE_SPACE     (4 * INFRARED_KASEIKYO_UNIT)
#define INFRARED_KASEIKYO_BIT1_MARK          INFRARED_KASEIKYO_UNIT
#define INFRARED_KASEIKYO_BIT1_SPACE         (3 * INFRARED_KASEIKYO_UNIT)
#define INFRARED_KASEIKYO_BIT0_MARK          INFRARED_KASEIKYO_UNIT
#define INFRARED_KASEIKYO_BIT0_SPACE         INFRARED_KASEIKYO_UNIT
#define INFRARED_KASEIKYO_REPEAT_PERIOD      130000
#define INFRARED_KASEIKYO_SILENCE            INFRARED_KASEIKYO_REPEAT_PERIOD
#define INFRARED_KASEIKYO_MIN_SPLIT_TIME     INFRARED_KASEIKYO_REPEAT_PAUSE_MIN
#define INFRARED_KASEIKYO_REPEAT_PAUSE_MIN   4000
#define INFRARED_KASEIKYO_REPEAT_PAUSE_MAX   150000
#define INFRARED_KASEIKYO_REPEAT_COUNT_MIN   1
#define INFRARED_KASEIKYO_REPEAT_MARK        INFRARED_KASEIKYO_PREAMBLE_MARK
#define INFRARED_KASEIKYO_REPEAT_SPACE       (INFRARED_KASEIKYO_REPEAT_PERIOD - 56000)
#define INFRARED_KASEIKYO_PREAMBLE_TOLERANCE 200 // us
#define INFRARED_KASEIKYO_BIT_TOLERANCE      120 // us
#define INFRARED_KASEIKYO_CARRIER_FREQUENCY  38000
#define INFRARED_KASEIKYO_DUTY_CYCLE         0.33f

// NEC protocol timings
#define INFRARED_NEC_PREAMBLE_MARK      9000
#define INFRARED_NEC_PREAMBLE_SPACE     4500
#define INFRARED_NEC_BIT1_MARK          560
#define INFRARED_NEC_BIT1_SPACE         1690
#define INFRARED_NEC_BIT0_MARK          560
#define INFRARED_NEC_BIT0_SPACE         560
#define INFRARED_NEC_REPEAT_PERIOD      110000
#define INFRARED_NEC_SILENCE            INFRARED_NEC_REPEAT_PERIOD
#define INFRARED_NEC_MIN_SPLIT_TIME     INFRARED_NEC_REPEAT_PAUSE_MIN
#define INFRARED_NEC_REPEAT_PAUSE_MIN   4000
#define INFRARED_NEC_REPEAT_PAUSE_MAX   150000
#define INFRARED_NEC_REPEAT_COUNT_MIN   1
#define INFRARED_NEC_REPEAT_MARK        9000
#define INFRARED_NEC_REPEAT_SPACE       2250
#define INFRARED_NEC_PREAMBLE_TOLERANCE 200 // us
#define INFRARED_NEC_BIT_TOLERANCE      120 // us

// Pioneer protocol timings
#define INFRARED_PIONEER_CARRIER_FREQUENCY  40000
#define INFRARED_PIONEER_DUTY_CYCLE         0.33f
#define INFRARED_PIONEER_PREAMBLE_MARK      8500
#define INFRARED_PIONEER_PREAMBLE_SPACE     4225
#define INFRARED_PIONEER_BIT1_MARK          500
#define INFRARED_PIONEER_BIT1_SPACE         1500
#define INFRARED_PIONEER_BIT0_MARK          500
#define INFRARED_PIONEER_BIT0_SPACE         500
#define INFRARED_PIONEER_PREAMBLE_TOLERANCE 200 // us
#define INFRARED_PIONEER_BIT_TOLERANCE      120 // us
#define INFRARED_PIONEER_SILENCE            26000
#define INFRARED_PIONEER_MIN_SPLIT_TIME     (INFRARED_PIONEER_SILENCE)
#define INFRARED_PIONEER_REPEAT_COUNT_MIN   2

// RC5 protocol timings
#define INFRARED_RC5_CARRIER_FREQUENCY 36000
#define INFRARED_RC5_DUTY_CYCLE        0.33f
#define INFRARED_RC5_PREAMBLE_MARK      0
#define INFRARED_RC5_PREAMBLE_SPACE     0
#define INFRARED_RC5_BIT                888 // half time-quant for 1 bit
#define INFRARED_RC5_PREAMBLE_TOLERANCE 200 // us
#define INFRARED_RC5_BIT_TOLERANCE      120 // us
#define INFRARED_RC5_SILENCE            (2700 * 10)
#define INFRARED_RC5_MIN_SPLIT_TIME     2700
#define INFRARED_RC5_REPEAT_COUNT_MIN   1

// RC6 protocol timings
#define INFRARED_RC6_CARRIER_FREQUENCY 36000
#define INFRARED_RC6_DUTY_CYCLE        0.33f
#define INFRARED_RC6_PREAMBLE_MARK      2666
#define INFRARED_RC6_PREAMBLE_SPACE     889
#define INFRARED_RC6_BIT                444 // half time-quant for 1 bit
#define INFRARED_RC6_PREAMBLE_TOLERANCE 200 // us
#define INFRARED_RC6_BIT_TOLERANCE      120 // us
#define INFRARED_RC6_SILENCE            (2700 * 10)
#define INFRARED_RC6_MIN_SPLIT_TIME     2700
#define INFRARED_RC6_REPEAT_COUNT_MIN   1

// RCA protocol timings
#define INFRARED_RCA_PREAMBLE_MARK  4000
#define INFRARED_RCA_PREAMBLE_SPACE 4000
#define INFRARED_RCA_BIT1_MARK      500
#define INFRARED_RCA_BIT1_SPACE     2000
#define INFRARED_RCA_BIT0_MARK      500
#define INFRARED_RCA_BIT0_SPACE     1000
#define INFRARED_RCA_REPEAT_PERIOD  8000
#define INFRARED_RCA_SILENCE        INFRARED_RCA_REPEAT_PERIOD
#define INFRARED_RCA_MIN_SPLIT_TIME     INFRARED_RCA_REPEAT_PAUSE_MIN
#define INFRARED_RCA_REPEAT_PAUSE_MIN   4000
#define INFRARED_RCA_REPEAT_PAUSE_MAX   150000
#define INFRARED_RCA_REPEAT_COUNT_MIN   1
#define INFRARED_RCA_REPEAT_MARK        INFRARED_RCA_PREAMBLE_MARK
#define INFRARED_RCA_REPEAT_SPACE       INFRARED_RCA_PREAMBLE_SPACE
#define INFRARED_RCA_PREAMBLE_TOLERANCE 200 // us
#define INFRARED_RCA_BIT_TOLERANCE      120 // us

// Samsung32 protocol timings
#define INFRARED_SAMSUNG_PREAMBLE_MARK      4500
#define INFRARED_SAMSUNG_PREAMBLE_SPACE     4500
#define INFRARED_SAMSUNG_BIT1_MARK          550
#define INFRARED_SAMSUNG_BIT1_SPACE         1650
#define INFRARED_SAMSUNG_BIT0_MARK          550
#define INFRARED_SAMSUNG_BIT0_SPACE         550
#define INFRARED_SAMSUNG_REPEAT_PAUSE_MIN   30000
#define INFRARED_SAMSUNG_REPEAT_PAUSE_MAX   140000
#define INFRARED_SAMSUNG_REPEAT_PAUSE1      46000
#define INFRARED_SAMSUNG_REPEAT_PAUSE2      97000
#define INFRARED_SAMSUNG_REPEAT_COUNT_MIN   1
#define INFRARED_SAMSUNG_MIN_SPLIT_TIME     5000
#define INFRARED_SAMSUNG_SILENCE            145000
#define INFRARED_SAMSUNG_REPEAT_MARK        4500
#define INFRARED_SAMSUNG_REPEAT_SPACE       4500
#define INFRARED_SAMSUNG_PREAMBLE_TOLERANCE 200 // us
#define INFRARED_SAMSUNG_BIT_TOLERANCE      120 // us

// SIRC protocol timings
#define INFRARED_SIRC_CARRIER_FREQUENCY  40000
#define INFRARED_SIRC_DUTY_CYCLE         0.33f
#define INFRARED_SIRC_PREAMBLE_MARK      2400
#define INFRARED_SIRC_PREAMBLE_SPACE     600
#define INFRARED_SIRC_BIT1_MARK          1200
#define INFRARED_SIRC_BIT1_SPACE         600
#define INFRARED_SIRC_BIT0_MARK          600
#define INFRARED_SIRC_BIT0_SPACE         600
#define INFRARED_SIRC_PREAMBLE_TOLERANCE 200 // us
#define INFRARED_SIRC_BIT_TOLERANCE      200 // us - increased for real-world signals
#define INFRARED_SIRC_SILENCE            10000
#define INFRARED_SIRC_MIN_SPLIT_TIME     (INFRARED_SIRC_SILENCE - 1000)
#define INFRARED_SIRC_REPEAT_PERIOD      45000
#define INFRARED_SIRC_REPEAT_COUNT_MIN   3

// Default carrier frequency and duty cycle for most protocols
#define INFRARED_COMMON_CARRIER_FREQUENCY 38000
#define INFRARED_COMMON_DUTY_CYCLE        0.33f

// NEC protocol carrier parameters
#define INFRARED_NEC_CARRIER_FREQUENCY    38000
#define INFRARED_NEC_DUTY_CYCLE           0.33f

#endif // INFRARED_TIMINGS_H 